import os


AWS_REGION = os.getenv('AWS_REGION')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_SECURITY_TOKEN = os.getenv('AWS_SECURITY_TOKEN')
AWS_SESSION_EXPIRATION = os.getenv('AWS_SESSION_EXPIRATION')
