name: CI-Python-3.7

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: Run test
      run: ./scripts/test.sh 37
