name: CI-Python-3.11

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Run test
      run: ./scripts/test.sh 311

    # report coverage on python 3.11
    - name: Upload coverage
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
