name: CI-Python-3.12

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run test
      run: ./scripts/test.sh 312

    # report coverage on python 3.12
    - name: Upload coverage
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
