name: Publish

on:
  push:
    tags:
    - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: build & publish
      run: ./scripts/publish.sh
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
