name: Publish

on:
  push:
    tags:
    - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: build & publish
      run: ./scripts/publish.sh
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
