name: Publish

on:
  push:
    tags:
    - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: build & publish
      run: ./scripts/publish.sh
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
